bot:
  token: "5905217606:AAFjONtp2QeekO60LkuxjYyvs6ZAxMgmAhg"
  name: "KekitaBot"
  handlers:
    meme:
      frequency: 20
      rate-limit: 3
      replies:
        - "Очевидно"
        - "Ты дебил?"
        - "Накладываю мандаторий"
        - "А я рассказывал тебе про KHTML?"
        - "Предсказуемо"
        - "Как же похуй"
        - "Пон"
        - "Ясно"
        - "Факт"
        - "А мог бы просто джаву взять..."
        - "Спасибо, подрочил"
        - "Это окно Овертона"
        - "Я участвовать в треугольника Карпмана не собираюсь"
        - "Звучит как слова жертвы"
        - "Я не собираюсь играть в спасителя и объяснять тебе что-то"
        - "Ты читал Цветы для Элджернона?
           Прочитай и поймёшь, почему я не мешаю другим людям прокачать свою зону роста)"
        - "Ты ведь понимаешь, что формируешь треугольники Карпмана безостановочно?)"
        - "Кто знаком с термином Окно Овертона?"
        - "Окно Овертона тут работать не будет)"
        - "1. Не участвую в треугольниках карпмана.
           2. Не проявляю сочувствие к нытикам.
           3. Не собираюсь вкладываться в твоё развитие.
           4. Ты уже неоднократно демонстрировал, какой ты Д'артаньян.
           5. Хочешь выговориться - иди у психологу, оплачивать ему время и пусть он копается в твоих проблемах.
           6. Ты сам просился сюда, и судя по всему, с прошлого раза выводов не сделал - заменил вспыльчивость комплексом угнетенности."

management:
  endpoints:
    web:
      exposure:
        include: heals,metrics,prometheus
  simple:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
  pattern.console: "-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [updateId - %X{updateId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  include-application-name: false